### ISSUE TITLE
Could not upload BPMN from Modeler app

### ISSUE THREAD

**Issue by lorrod** [AlexSKuznetsov/control-app#40]
I attempted to quickly start this project but encountered difficulty accessing the Zeebe endpoint from the Camunda Modeler. It shows an error: "Should point to a zeebe cluster".
<img width="318" alt="Screenshot 2023-07-06 at 16 09 35" src="https://github.com/AlexSKuznetsov/control-app/assets/46269337/b7188960-b935-4828-aff6-61bd5dd33d74">

I am currently using the latest version of the Modeler app and attempting to access Zeebe through `http://localhost:8080/engine-rest`.
There is no errors in log, I can access camunda endpoints such as `http://localhost:8080/camunda`

Here is what I get from zeebe expected endpoints
```
➜  control-app git:(main) curl http://localhost:8080/engine-rest
{"type":"NotFoundException","message":"RESTEASY003210: Could not find resource for full path: http://localhost:8080/engine-rest","code":null}% 
```
```
➜  control-app git:(main) curl http://localhost:8080/engine-rest/engine
[{"name":"default"}]
```

Do I need to have an extra setup? What can cause the problem?

**Comment by AlexSKuznetsov** [comment]
Hi @lorrod, it seems that you are using another version of the diagram. (Camunda platform 8)
Current project aimed to use Camunda platform 7 version. Make sure that when you create a diagram for 7 version.

![Screenshot 2023-07-06 at 11 22 14](https://github.com/AlexSKuznetsov/control-app/assets/47721260/cb752e2f-bc78-41d5-a451-81d1d83b5c54)
